import Script from 'next/script'
import './main.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Script src="https://kit.fontawesome.com/b111eba4a9.js" crossorigin="anonymous"></Script>
      <body id="root" className={inter.className}>
          {children}
      </body>
    </html>
  )
}
